version: "3"
services:
  tsapp:
    container_name: tsapp
    tty: true
    image: tsapp
    build:
      context: .
    volumes:
      - ./:/usr/tsapp/
      # node_modulesはgitでもdockerイメージでも保持したくないので
      # docker containerにデータボリュームとしてマウントし、
      # docker-compose build時にインストールする。
      - /usr/tsapp/node_modules
    command:
      sh -c "
      echo tsapp &&
      npx tsc src/index.ts &&
      node src/index.js
      "

